# Generated by Django 3.0.4 on 2020-03-08 04:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.PositiveIntegerField(default=0)),
                ('user_name', models.CharField(max_length=255)),
                ('correct_words', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
